------------------------------------------------------------------------------
-- Induction principle for N.
------------------------------------------------------------------------------

module Draft.FOTC.Data.Nat.Induction.Induction where

open import FOTC.Base

data N : D → Set where
  zN : N zero
  sN : ∀ {n} → N n → N (succ n)

indN : (P : D → Set) →
       P zero →
       (∀ {n} → N n → P n → P (succ n)) →
       ∀ {n} → N n → P n
indN P p0 h zN      = p0
indN P p0 h (sN Nn) = h Nn (indN P p0 h Nn)

-- Induction principle generated by Coq when we define the data type N in Set.
indN-Coq : (P : {d : D} → N d → Set) →
           P zN →
           (∀ {n} → (Nn : N n) → P Nn → P (sN Nn)) →
           ∀ {n} → (Nn : N n) → P Nn
indN-Coq P P0 h zN      = P0
indN-Coq P P0 h (sN Nn) = h Nn (indN-Coq P P0 h Nn)
