* About the second paper
** To comment/add
*** The handling of ATP stuff inside where clauses
**** The problems
**** This facilitate writing the ATP axioms. e.g.
LTC.Examples.GCD.Extra.S≤0-elim : {A : Set}{d : D} → succ d ≤ zero → A
*** The difference between predicates' definitions and functions' definitions
From Agda internal representation of clauses, both definitions are
equal, the only difference is in the type of the symbol.
*** The problem with eta and the existential
postulate
  D   : Set
  _≡_ : D → D → Set
  P   : (D → Set) → Set
  foo : (x : D) → P (λ y → y ≡ x)
  bar : (x : D) → P (λ y → x ≡ y)

foo and bar have different internal type because in bar Agda uses eta,
i.e. (_≡_ x) is the same as (λ y → x ≡ y).
*** Martin-Löf cite
From Peter:
Just a note. In one of Per Martin-Löf's first papers on
type theory he explicitly writes down translations of a number of well
known theories into type theory, including a translation of first
order intuitionistic predicate logic using Curry-Howard. This might
actually be useful to look at, and to cite.
* About the tool agda2atp
** Use
*** The following symbols are hard-coded, i.e. they should not changed
FOL false                  : ⊥
FOL true                   : ⊤
FOL negation               : ¬_
FOL conjunction            : _∧_
FOL disjunction            : _∨_
FOL implication            : _⇒_ or Agda functional space
FOL equivalence            : _↔_
FOL universal quantifier   : ∀D or Agda functional space
FOL existential quantifier : ∃D
FOL equality               : _≡_
*** Agda version
The tool agda2atp must be compiled using the same version of Agda that
is used to generate the Agda interface files.
* Others
** Using reflection.
From Ulf comments in AIMX
(http://wiki.portal.chalmers.se/agda/pmwiki.php?n=Main.AIMX)

<Ulf: magic function Set → FOL is hopeless. reflection is so much
better>

* Tags
** Tag 2010-11-06
Last Agda patch for this tag:

Wed Nov  3 15:03:26 COT 2010  Nils Anders Danielsson <nils.anders.danielsson@gmail.com>
  * Documented how --test can be enabled by default for darcs record.
